export const SHELVES_GET_SHELVES = 'SHELVES/GET_SHELVES'
export const SHELVES_GET_SHELVES_SUCCESS = 'SHELVES/GET_SHELVES_SUCCESS'
export const SHELVES_GET_SHELVES_ERROR = 'SHELVES/GET_SHELVES_ERROR'

export const SHELVES_UPDATE_SHELF = 'SHELVES/UPDATE_SHELF'
export const SHELVES_UPDATE_SHELF_SUCCESS = 'UPDATE/GET_SHELF_SUCCESS'
export const SHELVES_UPDATE_SHELF_ERROR = 'UPDATE/GET_SHELF_ERROR'
