export const SHELVES_GET_SHELVES = 'SHELVES/GET_SHELVES'
export const SHELVES_GET_SHELVES_SUCCESS = 'SHELVES/GET_SHELVES_SUCCESS'
export const SHELVES_GET_SHELVES_ERROR = 'SHELVES/GET_SHELVES_ERROR'

//API

export const API_URL_NAME = 'shelves'