export const SHELVES_GET_SHELVES = 'SHELVES/GET_SHELVES'
export const SHELVES_GET_SHELVES_SUCCESS = 'SHELVES/GET_SHELVES_SUCCESS'
export const SHELVES_GET_SHELVES_ERROR = 'SHELVES/GET_SHELVES_ERROR'

export const SHELVES_CREATE_SHELF = 'SHELVES/CREATE_SHELF'
export const SHELVES_CREATE_SHELF_SUCCESS = 'SHELVES/CREATE_SHELF_SUCCESS'
export const SHELVES_CREATE_SHELF_ERROR = 'SHELVES/CREATE_SHELF_ERROR'

export const SHELVES_UPDATE_SHELF = 'SHELVES/UPDATE_SHELF'
export const SHELVES_UPDATE_SHELF_SUCCESS = 'SHELVES/UPDATE_SHELF_SUCCESS'
export const SHELVES_UPDATE_SHELF_ERROR = 'SHELVES/UPDATE_SHELF_ERROR'

export const SHELVES_REMOVE_SHELF = 'SHELVES/REMOVE_SHELF'
export const SHELVES_REMOVE_SHELF_SUCCESS = 'SHELVES/REMOVE_REMOVE_SUCCESS'
export const SHELVES_REMOVE_SHELF_ERROR = 'SHELVES/REMOVE_REMOVE_ERROR'