export const BOOKS_GET_BOOKS = 'BOOKS/GET_BOOKS'
export const BOOKS_GET_BOOKS_SUCCESS = 'BOOKS/GET_BOOKS_SUCCESS'
export const BOOKS_GET_BOOKS_ERROR = 'BOOKS/GET_BOOKS_ERROR'

//API

export const API_URL_NAME = 'books'