export const BOOKS_GET_BOOKS = 'BOOKS/GET_BOOKS'
export const BOOKS_GET_BOOKS_SUCCESS = 'BOOKS/GET_BOOKS_SUCCESS'
export const BOOKS_GET_BOOKS_ERROR = 'BOOKS/GET_BOOKS_ERROR'

export const BOOKS_UPDATE_BOOK = 'BOOKS/UPDATE_BOOK'
export const BOOKS_UPDATE_BOOK_SUCCESS = 'BOOKS/UPDATE_BOOK_SUCCESS'
export const BOOKS_UPDATE_BOOK_ERROR = 'BOOKS/UPDATE_BOOK_ERROR'
