export const BOOKS_GET_BOOKS = 'BOOKS/GET_BOOKS'
export const BOOKS_GET_BOOKS_SUCCESS = 'BOOKS/GET_BOOKS_SUCCESS'
export const BOOKS_GET_BOOKS_ERROR = 'BOOKS/GET_BOOKS_ERROR'

export const BOOKS_CREATE_BOOK = 'BOOKS/CREATE_BOOK'
export const BOOKS_CREATE_BOOK_SUCCESS = 'BOOKS/CREATE_BOOK_SUCCESS'
export const BOOKS_CREATE_BOOK_ERROR = 'BOOKS/CREATE_BOOK_ERROR'

export const BOOKS_UPDATE_BOOK = 'BOOKS/UPDATE_BOOK'
export const BOOKS_UPDATE_BOOK_SUCCESS = 'BOOKS/UPDATE_BOOK_SUCCESS'
export const BOOKS_UPDATE_BOOK_ERROR = 'BOOKS/UPDATE_BOOK_ERROR'

export const BOOKS_REMOVE_BOOK = 'BOOKS/REMOVE_BOOK'
export const BOOKS_REMOVE_BOOK_SUCCESS = 'BOOKS/REMOVE_BOOK_SUCCESS'
export const BOOKS_REMOVE_BOOK_ERROR = 'BOOKS/REMOVE_BOOK_ERROR'
