//Actions

export const AUTHENTICATION_LOGIN = 'AUTHENTICATION/LOGIN'
export const AUTHENTICATION_LOGIN_ERROR = 'AUTHENTICATION/LOGIN_ERROR'
export const AUTHENTICATION_LOGIN_SUCCESS = 'AUTHENTICATION/LOGIN_SUCCESS'

export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION/LOGOUT'

//Others

export const API_URL = 'http://192.168.1.107:5000/login'

export const AUTHENTICATION_TOKEN_KEY = 'AUTHENTICATION_KEY'
