//Actions

export const AUTHENTICATION_LOGIN = 'AUTHENTICATION/LOGIN'
export const AUTHENTICATION_LOGIN_ERROR = 'AUTHENTICATION/LOGIN_ERROR'
export const AUTHENTICATION_LOGIN_SUCCESS = 'AUTHENTICATION/LOGIN_SUCCESS'

export const AUTHENTICATION_GET_AUTH_TOKEN = 'AUTHENTTICATION/GET_AUTH_TOKEN'
export const AUTHENTICATION_GET_AUTH_TOKEN_ERROR = 'AUTHENTTICATION/GET_AUTH_TOKEN_ERROR'
export const AUTHENTICATION_GET_AUTH_TOKEN_SUCCESS = 'AUTHENTTICATION/GET_AUTH_TOKEN_SUCCESS'

export const AUTHENTICATION_GET_REFRESH_TOKEN = 'AUTHENTTICATION/GET_REFRESH_TOKEN'
export const AUTHENTICATION_GET_REFRESH_TOKEN_ERROR = 'AUTHENTTICATION/GET_REFRESH_TOKEN_ERROR'
export const AUTHENTICATION_GET_REFRESH_TOKEN_SUCCESS = 'AUTHENTTICATION/GET_REFRESH_TOKEN_SUCCESS'

export const AUTHENTICATION_HIDE_ERROR_MODAL = 'AUTHENTICATION/HIDE_ERROR_MODAL'

export const AUTHENTICATION_TOGGLE_SECURE_TEXT_ENTRY = 'AUTHENTICATION/TOGGLE_SECURE_TEXT_ENTRY'

export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION/LOGOUT'

//API

export const API_URL_NAME = 'login'
