export const AUTHENTICATION_LOGIN = 'AUTHENTICATION/LOGIN'
export const AUTHENTICATION_LOGIN_ERROR = 'AUTHENTICATION/LOGIN_ERROR'
export const AUTHENTICATION_LOGIN_SUCCESS = 'AUTHENTICATION/LOGIN_SUCCESS'

export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION/LOGOUT'