export const SEARCH_SEARCH_BOOK = 'SEARCH/SEARCH_BOOK'
export const SEARCH_SEARCH_BOOK_SUCCESS = 'SEARCH/SEARCH_BOOK_SUCCESS'
export const SEARCH_SEARCH_BOOK_ERROR = 'SEARCH/SEARCH_BOOK_ERROR'

export const SEARCH_RESET_SEARCH = 'SEARCH/RESET_SEARCH'
